CriarFiltrosTutorial.create(title: 'Calendário – funcionalidades', date: '03 / 02 / 2020')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Calendário – funcionalidades')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Na aba “Calendário” do Webmail, o usuário encontra as seguintes opções:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '1. Nessa opção o usuário pode criar novos eventos. Também é possível criar eventos clicando em cima da hora desejada no calendário para saber como criar eventos;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '2. Nessa opção o usuário pode imprimir o calendário, exportar ou importar eventos;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '3. Aqui o usuário pode visualizar e escolher o ano, o mês e o dia desejado;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '4. É possível criar vários tipos de calendários e nessa opção o usuário consegue administrar e criar os seus calendários;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '5. O usuário pode escolher o modo de visualização do calendário;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '6. Indica a data que está sendo mostrada no calendário;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '7. O usuário pode procurar algum evento no calendário;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '8. Nessa opção o usuário pode avançar ou voltar a data no calendário;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '9. É onde o usuário visualiza o calendário.')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/62/center_CalendarioFuncionalidades1.jpg', caption: 'Imagem 1')
