Tutorial.create(title: 'Como executar um conjunto de backup', date: '17 / 02 / 2020')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Como executar um conjunto de backup')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique no ícone “Backup” no menu:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione o conjunto que deseja executar. Se quiser modificar as configurações do tipo Delta, os destinos e a política de retenção, clique em “mostrar a opção avançada”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na opção avançada, na parte “Tipo delta no arquivo”, o usuário encontra as seguintes opções:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Completo: o backup captura todos os dados que deseja proteger.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Diferencial: o backup diferencial captura apenas as mudanças feitas comparado com o último arquivo')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Incremental: o backup incremental captura apenas as mudanças feitas em comparação com o último arquivo completo ou delta carregado (ou seja, as mudanças desde o último backup incremental).')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione a opção desejada e clique em “Backup”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Pronto! Seu backup foi concluído com êxito.')
