Tutorial.create(title: 'Criando conjunto de backup', date: '17 / 02 / 2020')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Criando Conjunto de Backup')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique no ícone “Conjuntos de Backup” no menu principal:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique no ícone “+” ao lado de “Adicionar novo conjunto de backup”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione o “Nome” do seu conjunto e o tipo de arquivos que será feito esse backup, dependendo de qual tipo for selecionado outras informações podem ser solicitadas, nesse caso selecionaremos o tipo “Backup de arquivos”, clique em avançar:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione os arquivos e pastas que deseja realizar o backup, também é possível aplicar filtros. Em “Eu gostaria de escolher os arquivos para backup” é possível escolher arquivos específicos para o backup:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Fonte de backup avançado” selecione a pasta desejada para mostrar todo o conteúdo:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Se desejar fazer o backup de arquivos individuais, ao invés de todos os arquivos da pasta, clique em “Visualizar arquivos”.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Uma lista vai aparecer no lado direito, marque os arquivos desejados e clique em “Ok”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Agendar”, o usuário pode configurar um agendamento para executar automaticamente o seu backup.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Para criar um agendamento, habilite “Executar o backup agendado para este conjunto de backup”, e clique no ícone “+”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Digite os dados do novo agendamento e clique em “Ok”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Destino”, escolha o modo de backup:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione a opção desejada:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Sequencial: faz o backup de um conjunto por vez;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Simultâneo: faz o backup de todos os conjuntos ao mesmo tempo;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após escolher, clique no ícone “+”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Novo destino de armazenamento/pool de destino”, selecione o nosso servidor “SkymailCBS” na opção “Armazenamento de destino” e clique em “Ok”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “OpenDirect”, há a opção de habilitar essa função:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'O OpenDirect serve para restaurar pastas individuais dentro de grandes arquivos compactados/de imagem (exemplo: zip, ISO, RAR), sem a necessidade de restaurar o arquivo completo.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Obs: Se ativado no conjunto de backup, não é possível desabilitar depois e vice versa.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após selecionar, clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Obs: Se ativado, a etapa “Criptografia” será pulada;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Criptografia”, a função “Criptografar dados de backup” já vem ativada e oferece a opção mais segura.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'O usuário pode escolher o tipo de criptografia:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Padrão: uma chave de criptografia com 44 caracteres alfa numéricos será aleatoriamente gerado pelo sistema;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Senha do usuário: a chave de criptografia será a mesma senha do login no momento em que este conjunto de backup foi criado.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Personalizado: o usuário pode escolher suas próprias configurações;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após definir as configurações, clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Se ativado, na próxima janela será mostrado a chave de criptografia de acordo com a opção selecionada.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após salvar, clique em “Confirmar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na próxima janela, o usuário vai inserir as credenciais de login do Windows para autenticação de usuário.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Essa opção irá aparecer se o usuário criou um novo agendamento na opção “Agendar”.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Digite as informações e clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Pronto! O conjunto de backup foi criado!')
