Tutorial.create(title: 'Restauração de Arquivos')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Restauração de Arquivos')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Clique no ícone “Restauração” no menu:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Todos os conjuntos de backup serão mostrados, selecione qual será restaurado:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione de onde quer restaurar os dados:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione se deseja restaurar arquivos de um conjunto de backup específico, ou de todos os arquivos disponíveis, então selecione os arquivos ou pastas que você gostaria de restaurar.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Essas são as duas opções do menu “Selecione o que quer restaurar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Escolha de arquivos de trabalho: esta opção permite selecionar uma versão de backup a partir de uma data e hora específica.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Escolha todos os arquivos: restaura todas as versões disponíveis de backup do conjunto;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione as pastas que deseja recuperar e clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na janela “Escolha onde Arquivos deve ser restaurado”, escolha local onde ficarão os arquivos restaurados:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Localização original: A restauração será feita no mesmo local que o backup fonte;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Local alternativo: O usuário pode restaurar os dados para outro local do computador;')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após selecionar, clique em “Avançar”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Selecione o diretório temporário que será salvo os seus arquivos antes da restauração ser completada (Obs: recomendamos manter no diretório padrão).')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após selecionar, clique em “Restauração”:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Quando a restauração estiver concluída, aparecerá a mensagem: “Restauração concluída com êxito”.')
