Tutorial.create(title: 'Instalação do client SkyBackup', date: '17 / 02 / 2020')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Instalação do Client SkyBackup')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Para baixar o cliente de backup acesse:')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Backup Skymail')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após o download do client de backup, inicie a instalação, abra o client e aparecerá essa tela abaixo, clique em “Avançar”.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Na próxima tela selecione a opção “Aceito o contrato” e clique novamente em “Avançar”')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Defina a pasta de destino da instalação dos arquivos, se optar não manter o padrão, e clique novamente em “Avançar”.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Escolha a opção de quem poderá utilizar o software instalado, por padrão sempre recomendamos setar a opção “Apenas eu”')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Confirme todas as configurações setadas e clique em “Instalar”.')
TutorialContent.create(tutorial_id: Tutorial.last.id, content: 'Após todo o processo de instalação, clique em “Concluir”, se a opção “Iniciar SkymailBP” estiver selecionada o client abrirá logo em seguida.')
