ComoImportarContatosTutorial.create(title: 'Como importar contatos', date: '03 / 02 / 2020')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Como importar contatos')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'No Webmail, clique em “Contatos”:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Clique em “Importar”:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Para prosseguir, será necessário importar um arquivo csv.')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Faça download do modelo através desse link : https://ajuda.skymail.com.br/wp-content/uploads/2018/06/Exemplo-contatos.csv')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Após fazer o download, abra o arquivo:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Preencha a coluna com os contatos que deseja importar ( é a única coluna obrigatória):')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Após preencher a coluna, salve o arquivo (csv separado por vírgula)')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Após salvar, abra o arquivo com o Bloco de Notas:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Substitua todos os ” ; ” por ” , “:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Salve o arquivo')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'De volta no Webmail, selecione o arquivo criado:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Selecione as opções desejadas:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Adicionar contatos para: Aqui o usuário escolhe a pasta que os contatos serão importados.')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Importar atribuições do grupo: O usuário pode escolher as opções do grupo')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Substituir o catálogo de endereços atual: Os contatos importados vão substituir o catálogo atual.')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Após selecionar, clique em “Importar”:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Clique em “Concluído”:')
ComoImportarContatosTutorialContent.create(tutorial_id: ComoImportarContatosTutorial.last.id, content: 'Pronto! Os contatos foram importados com sucesso!')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/49/center_1.png', caption: 'Imagem 1')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/50/center_2.png', caption: 'Imagem 2')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/51/center_3.png', caption: 'Imagem 3')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/52/center_4.png', caption: 'Imagem 4')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/53/center_5.png', caption: 'Imagem 5')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/54/center_6.png', caption: 'Imagem 6')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/55/center_7.png', caption: 'Imagem 7')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/56/center_8.png', caption: 'Imagem 8')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/57/center_9.png', caption: 'Imagem 9')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/58/center_10.png', caption: 'Imagem 10')
Image.create(tutorial_id: ComoImportarContatosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/59/center_11.png', caption: 'Imagem 11')
