tutorial = Tutorial.create(title: 'Como importar contatos', date: '03 / 02 / 2020')
TutorialContent.create(tutorial: tutorial, content: 'Como importar contatos')
TutorialContent.create(tutorial: tutorial, content: 'No Webmail, clique em “Contatos”:')
TutorialContent.create(tutorial: tutorial, content: 'Clique em “Importar”:')
TutorialContent.create(tutorial: tutorial, content: 'Para prosseguir, será necessário importar um arquivo csv.')
TutorialContent.create(tutorial: tutorial, content: 'Faça download do modelo através desse link : https://ajuda.skymail.com.br/wp-content/uploads/2018/06/Exemplo-contatos.csv')
TutorialContent.create(tutorial: tutorial, content: 'Após fazer o download, abra o arquivo:')
TutorialContent.create(tutorial: tutorial, content: 'Preencha a coluna com os contatos que deseja importar ( é a única coluna obrigatória):')
TutorialContent.create(tutorial: tutorial, content: 'Após preencher a coluna, salve o arquivo (csv separado por vírgula)')
TutorialContent.create(tutorial: tutorial, content: 'Após salvar, abra o arquivo com o Bloco de Notas:')
TutorialContent.create(tutorial: tutorial, content: 'Substitua todos os ” ; ” por ” , “:')
TutorialContent.create(tutorial: tutorial, content: 'Salve o arquivo')
TutorialContent.create(tutorial: tutorial, content: 'De volta no Webmail, selecione o arquivo criado:')
TutorialContent.create(tutorial: tutorial, content: 'Selecione as opções desejadas:')
TutorialContent.create(tutorial: tutorial, content: 'Adicionar contatos para: Aqui o usuário escolhe a pasta que os contatos serão importados.')
TutorialContent.create(tutorial: tutorial, content: 'Importar atribuições do grupo: O usuário pode escolher as opções do grupo')
TutorialContent.create(tutorial: tutorial, content: 'Substituir o catálogo de endereços atual: Os contatos importados vão substituir o catálogo atual.')
TutorialContent.create(tutorial: tutorial, content: 'Após selecionar, clique em “Importar”:')
TutorialContent.create(tutorial: tutorial, content: 'Clique em “Concluído”:')
TutorialContent.create(tutorial: tutorial, content: 'Pronto! Os contatos foram importados com sucesso!')
