ComporEmailTutorial.create(title: 'Compor e-mail – funcionalidades', date: '03 / 02 / 2020')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Compor e-mail – funcionalidades')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Dentro da opção “Criar e-mail“, você encontra essas funcionalidades:')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Enviar: Essa opção envia o e-mail que o usuário criou;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Salvar: Essa opção salva o e-mail criado como rascunho, caso o usuário queira editá-lo ou enviá-lo depois;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Cancelar: Essa opção serve para cancelar o envio do e-mail e volta para tela principal do Webmail;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Anexar: Essa opção permite que o usuário adicione um arquivo para enviar junto com o e-mail. ')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Revisar: Nessa opção o usuário pode visualizar se há algum erro na mensagem.')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Ao lado das abas explicadas acima, o usuário pode mudar o idioma, colocar resposta e assinatura;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'De: É o remetente do e-mail;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Para: Nessa opção, o usuário define quem receberá o e-mail;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Cópia: O usuário escolhe quem irá receber a cópia do e-mail. Também existe a opção cópia oculta, na qual os destinatários não podem visualizar quem recebeu a cópia;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Assunto: O usuário descreve uma introdução sobre o conteúdo do e-mail. Também é possível definir a prioridade do e-mail (Mais Baixa, Baixa, Normal, Alta e Mais Alta);')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Nesse campo, o usuário vai escrever a mensagem que deseja enviar. Há duas maneiras para escrever a mensagem: texto simples e HTML (o usuário pode editar a mensagem);')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '1. Deixa a mensagem em Negrito;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '2. Deixa a mensagem em Itálico;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '3. Sublinha a mensagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '4. Alinha a mensagem para o lado esquerdo;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '5. Centraliza a mensagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '6. Alinha a mensagem para o lado direito;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '7. Alinha ambas as bordas de cada linha com a margem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '8. Cria marcadores (tópicos);')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '9. Cria uma lista numerada;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '10. Diminui o espaço em relação à margem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '11. Aumenta o espaço em relação à margem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '12. Digite da esquerda para a direita;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '13. Digite da direita para a esquerda;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '14. Coloque aspas;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '15. O usuário pode escolher a cor do texto;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '16. O usuário pode escolher a cor do fundo do texto;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '17. O usuário pode escolher a fonte que deseja;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '18. O usuário pode escolher o tamanho da fonte;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '19. O usuário pode inserir ou editar um link na mensagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '20. Remove o link da mensagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '21. O usuário pode adicionar tabelas;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '22. Serve para inserir caracteres especiais (Exemplo: Ö, Ü);')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '23. O usuário pode inserir ou editar uma imagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '24. O usuário pode inserir ou editar um vídeo;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '24. O usuário pode ver o código fonte da mensagem;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '26. Ferramenta que localiza e substitui as palavras que o usuário deseja;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '27. Serve para desfazer uma palavra ou letra que o usuário deseja;')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: '28. Serve para refazer algo que o usuário apagou.')
ComporEmailTutorialContent.create(tutorial_id: ComporEmailTutorial.last.id, content: 'Pronto! Essas são as funcionalidades de um e-mail!')
Image.create(tutorial_id: ComporEmailTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/5/center_imagem1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: ComporEmailTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/6/center_imagem2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: ComporEmailTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/7/center_imagem3.jpg', caption: 'Imagem 3')
Image.create(tutorial_id: ComporEmailTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/8/center_imagem4.jpg', caption: 'Imagem 4')
Image.create(tutorial_id: ComporEmailTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/9/center_imagem5.jpg', caption: 'Imagem 5')
