CriarPastasTutorial.create(title: 'Como criar pastas', date: '03 / 02 / 2020')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Pastas')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Nessa opção, o usuário consegue visualizar e editar todas as pastas do e-mail, além de criar novas pastas:')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Dentro de cada pasta, o usuário encontra as seguintes informações:')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Nome da pasta: mostra o nome da pasta selecionada;')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Visualização em lista: o usuário pode escolher entre lista ou agrupamento por assunto;')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Mensagens: mostra a quantidade de mensagens;')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Tamanho: mostra o espaço ocupado pelas mensagens;')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Política de retenção de Mensagens: o usuário pode excluir as mensagens permanentemente ou enviá-las para lixeira. Também é possível escolher o tempo de retenção.')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Como criar pasta:')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Existem duas maneiras de criar pasta:')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Na tela principal do e-mail, clique no ícone “Ações para as pastas”:')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'Clique em “Nova pasta“, digite o nome e pronto!')
CriarPastasTutorialContent.create(tutorial_id: CriarPastasTutorial.last.id, content: 'O usuário também pode ir em “Configurações”, “Pastas”, “Criar” e pronto!')
Image.create(tutorial_id: CriarPastasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/14/center_pastas1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: CriarPastasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/15/center_pastas2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: CriarPastasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/16/center_pastas3.jpg', caption: 'Imagem 3')
Image.create(tutorial_id: CriarPastasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/17/center_pastas4.jpg', caption: 'Imagem 4')
