CriarFiltrosTutorial.create(title: 'Como criar filtros', date: '03 / 02 / 2020')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Filtros')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Em “Configurações“, clique em “Filtros“:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Clique em “Criar“:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Definição de filtro')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Nome do filtro: o usuário escolhe um nome para o filtro criado;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Para e-mails recebidos: nessa opção o usuário vai definir as regras para o filtro;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Causando todas as seguintes regras: o filtro só será aplicado se encaixar em todas as regras;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Causando qualquer das seguintes regras: o filtro será aplicado se a mensagem se encaixar em qualquer uma das regras;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Todas as mensagens: todas as mensagens recebidas vão passar pelo filtro;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Na seguinte opção o usuário vai definir as regras que deseja e decidir qual ação será executada;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Após preencher, clique em “Salvar” e o filtro já estará ativado.')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Para desativar o filtro')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Se quiser desativar o filtro, clique em “Opções“, selecione “Habilitar/Desabilitar” ou clique no filtro que deseja desabilitar e selecione a opção “Filtro desativado“:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Exemplo')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Todos os e-mails do remetente:”[email protected]”, vão para a pasta.“Exemplo”:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Pronto! O filtro foi criado com sucesso!')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/20/center_como-criar-filtros1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/21/center_como-criar-filtro2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/22/center_como-criar-filtros3.jpg', caption: 'Imagem 3')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/23/center_como-criar-filtros4.jpg', caption: 'Imagem 4')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/24/center_como-criar-filtros5.jpg', caption: 'Imagem 5')
