DesabilitarConfirmacaoEntregaTutorial.create(title: 'Como desabilitar a confirmação de entrega', date: '03 / 02 / 2020')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Como desabilitar a confirmação de entrega')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Através do Webmail:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Você pode setar essa opção quando clicar em escrever e-mail. Ou pode configurar para deixar padrão automatizando para novas mensagens.')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'No momento de escrever, clicando em criar e-mail.')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Ou desabilitando em configurações.')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Vá na aba “preferências”:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Clique em “Redigir mensagens” e desabilite a opção “sempre pedir confirmação de entrega”:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Clique em “Salvar”.')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Pronto!')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Através do Outlook:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Clique em “Arquivo”:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Clique em ‘Opções”:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Na janela, clique em “E-mail” e na opção “Acompanhamento”, desabilite a opção “Confirmação de entrega garantindo que a mensagem foi entregue ao servidor de email do destinatário”:')
DesabilitarConfirmacaoEntregaTutorialContent.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, content: 'Pronto!')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/30/center_1.png', caption: 'Imagem 1')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/31/center_2.png', caption: 'Imagem 2')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/32/center_3.png', caption: 'Imagem 3')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/33/center_4.png', caption: 'Imagem 4')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/34/center_5.png', caption: 'Imagem 5')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/35/center_6.png', caption: 'Imagem 6')
Image.create(tutorial_id: DesabilitarConfirmacaoEntregaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/36/center_7.png', caption: 'Imagem 7')
