InserirTrocarFotoNoWebmailTutorial.create(title: 'Inserir ou trocar foto no Webmail', date: '03 / 02 / 2020')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'Colocar ou trocar foto no Webmail')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'No Webmail, clique em “Configurações” e em seguida clique em “Informações de usuário“:')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'Em “Imagem para o perfil“, selecione a opção:')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: '1-Para buscar a foto;')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: '2-Para remover a foto atual;')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'Para colocar a foto, clique na opção “1“, e selecione a imagem que deseja e clique em “Abrir“:')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'Selecione a parte que deseja da foto e clique em “Cortar“:')
InserirTrocarFotoNoWebmailTutorialContent.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, content: 'Pronto! Sua imagem foi colocada com sucesso!')
Image.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, remote_image_url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/37/center_InserirTrocarFotoNoWebmail1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, remote_image_url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/38/center_InserirTrocarFotoNoWebmail2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, remote_image_url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/39/center_InserirTrocarFotoNoWebmail3.jpg', caption: 'Imagem 3')
Image.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, remote_image_url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/40/center_InserirTrocarFotoNoWebmail4.jpg', caption: 'Imagem 4')
Image.create(tutorial_id: InserirTrocarFotoNoWebmailTutorial.last.id, remote_image_url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/41/center_InserirTrocarFotoNoWebmail5.jpg', caption: 'Imagem 5')
