MensagemDeFeriasTutorial.create(title: 'Mensagem de férias', date: '03 / 02 / 2020')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Mensagem de férias')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Para configurar a sua mensagem de férias no Webmail, clique em seu nome no canto superior direito e em seguida clique em “Mensagem de Férias“: (ou entre em “Configurações” e em seguida clique em “Férias“):')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Nesta página, preencha todos os campos:')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Assunto: O usuário pode definir um assunto pra mensagem de férias;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Conteúdo: neste campo, o usuário vai digitar a mensagem que deseja usar durante o período de férias;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Início das férias: o usuário informa quando começam suas férias, e quando a mensagem começará a ser enviada aos remetentes;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Término das férias: o usuário informa quando suas férias finalizam, e automaticamente, sua mensagem não será mais enviada;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Estado: neste campo o usuário define se deseja deixar ativado a sua mensagem de férias (ligado), ou se deseja usá-la em outro momento (desligado);')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Após concluir, clique em “Salvar”:')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Opções avançadas')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Responder endereço do remetente: o usuário pode adicionar um e-mail que deseja responder. Funciona somente se existir alias (apelido) atrelado a conta.')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Meus endereços de e-mail: o usuário seleciona qual serão os endereços de e-mail adicionados, se tiver alias, tbm é possível inseri-los;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Intervalo de resposta: o usuário define o tempo de intervalo entre as repostas;')
MensagemDeFeriasTutorialContent.create(tutorial_id: MensagemDeFeriasTutorial.last.id, content: 'Ações para mensagens recebidas: o usuário define o que deseja fazer com as mensagens recebidas no período de férias (pode manter a mensagem, descartá-la, redirecioná-la para outra conta ou enviar uma cópia para outra conta).')
Image.create(tutorial_id: MensagemDeFeriasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/25/center_MensagemDeFerias1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: MensagemDeFeriasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/26/center_MensagemDeFerias2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: MensagemDeFeriasTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/27/center_MensagemDeFerias3.jpg', caption: 'Imagem 3')
