tutorial = Tutorial.create(title: 'Como pré-configurar e utilizar uma resposta', date: '03 / 02 / 2020')
TutorialContent.create(tutorial: tutorial, content: 'Respostas – Webmail')
TutorialContent.create(tutorial: tutorial, content: 'A aba respostas serve para o usuário criar mensagens para responder um e-mail.')
TutorialContent.create(tutorial: tutorial, content: 'Para criar uma resposta:')
TutorialContent.create(tutorial: tutorial, content: 'Em “Configurações“, clique na aba “Respostas” e selecione a opção “Criar“:')
TutorialContent.create(tutorial: tutorial, content: 'Coloque um nome, digite a mensagem que deseja manter pré-configurada e clique em “Salvar“:')
TutorialContent.create(tutorial: tutorial, content: 'Pronto! Sua resposta foi criada com sucesso”')
TutorialContent.create(tutorial: tutorial, content: 'Para utilizar a resposta:')
TutorialContent.create(tutorial: tutorial, content: 'No e-mail, clique em “…“, como mostra a imagem abaixo:')
TutorialContent.create(tutorial: tutorial, content: 'Clique em “Inserir uma resposta“:')
TutorialContent.create(tutorial: tutorial, content: 'Selecione a resposta que deseja utilizar:')
TutorialContent.create(tutorial: tutorial, content: 'Pronto! Sua mensagem foi inserida no e-mail com sucesso!')
