ComoPreconfigurarUtilizarRespostaTutorial.create(title: 'Como pré-configurar e utilizar uma resposta', date: '03 / 02 / 2020')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Respostas – Webmail')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'A aba respostas serve para o usuário criar mensagens para responder um e-mail.')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Para criar uma resposta:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Em “Configurações“, clique na aba “Respostas” e selecione a opção “Criar“:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Coloque um nome, digite a mensagem que deseja manter pré-configurada e clique em “Salvar“:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Pronto! Sua resposta foi criada com sucesso”')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Para utilizar a resposta:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'No e-mail, clique em “…“, como mostra a imagem abaixo:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Clique em “Inserir uma resposta“:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Selecione a resposta que deseja utilizar:')
ComoPreconfigurarUtilizarRespostaTutorialContent.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, content: 'Pronto! Sua mensagem foi inserida no e-mail com sucesso!')
Image.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/44/center_respostas1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/45/center_respostas2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/46/center_ComoPreConfigurarEUtilizarUmaResposta3.jpg', caption: 'Imagem 3')
Image.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/47/center_ComoPreConfigurarEUtilizarUmaResposta4.jpg', caption: 'Imagem 4')
Image.create(tutorial_id: ComoPreconfigurarUtilizarRespostaTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/48/center_ComoPreConfigurarEUtilizarUmaResposta5.jpg', caption: 'Imagem 5')
