CriarFiltrosTutorial.create(title: 'Contatos – funcionalidades', date: '03 / 02 / 2020')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Contatos – funcionalidades')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '1. O usuário pode importar seus contatos através de um arquivo;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '2. Nessa opção, o usuário pode exportar um contato;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '3. O usuário consegue exportar todos os contatos selecionados;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '4. Essa opção permite que o usuário escreva uma mensagem para o contato selecionado;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '5. Local onde o usuário pode criar e gerenciar seus grupos;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '6. Onde o usuário adiciona um contato;')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: '7. Local onde é mostrado a lista de contatos.')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/68/center_ContatosFuncionalidades1__1_.jpg', caption: 'Imagem 1')
