CriarFiltrosTutorial.create(title: 'Como exportar um contato', date: '04 / 02 / 2020')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Como exportar um contato')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Na aba “Contatos” do Webmail, clique no contato que deseja exportar:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Clique em “Exportar”')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'O navegador vai fazer o download do arquivo no formato vCard:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Pronto! O contato foi exportado com sucesso!')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/71/center_ComoExportarContato1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/72/center_ComoExportarContato2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/73/center_ComoExportarContato3.jpg', caption: 'Imagem 3')
