CriarFiltrosTutorial.create(title: 'Como exportar um grupo de contatos', date: '04 / 02 / 2020')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Como exportar um grupo de contatos')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Na aba “Contatos” do Webmail, clique no grupo de contatos que deseja exportar:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Clique em “Exportar Todos“:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'O navegador vai fazer o download do arquivo no formato vCard:')
CriarFiltrosTutorialContent.create(tutorial_id: CriarFiltrosTutorial.last.id, content: 'Pronto! O grupo de contatos foi exportado com sucesso!')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/79/center_ComoExportarUmGrupoDeContatos1.jpg', caption: 'Imagem 1')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/80/center_ComoExportarUmGrupoDeContatos2.jpg', caption: 'Imagem 2')
Image.create(tutorial_id: CriarFiltrosTutorial.last.id, url: 'https://cdn1.agenciaw3.digital//uploads/rails_admin_content_builder/content_builder_image/image/81/center_ComoExportarUmGrupoDeContatos3.jpg', caption: 'Imagem 3')
