BackupPerdidoTutorial.create(title: 'Backup Perdido', date: '17 / 02 / 2020')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Backup Perdido')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Principais motivos para backup perdido ao usar SkyBackup Software.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'A seguir estão os 8 principais motivos para as falhas de backups agendados e suas resoluções.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 1: A máquina foi desligada ou colocada no modo de hibernação no horário de início do backup agendado.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Verifique se a máquina está ligada ou hibernada no horário de início do backup programado.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 2: A máquina não está conectada à rede, portanto, não tem acesso ao servidor de backup.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Conectar a máquina na rede.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 3: Pode ser que a máquina se conecta à Internet através de um servidor proxy, pode ocorrer de ter largura de banda ou restrição de acesso no servidor proxy interrompendo a conexão do agente aos servidores de backup da skymail.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Edite a largura de banda ou a restrição de acesso no servidor proxy para permitir que o agente cliente skybackup se conecte ao servidor skymail durante a janela de backup.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 4: A configuração do firewall foi alterada na máquina ou na rede.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Edite a configuração do firewall para permitir que o agente cliente Skybackup se conecte ao servidor Skymail via HTTP e HTTPS.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 5: O serviço de agendador de tarefas do windows para o agente de backup não está em execução.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Reinicie os serviços Skybackup e valide se o próximo backup agendado pode ser restabelecido. Um boot na máquina também pode ajudar, depois do boot abra o agente de backup.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 6: A senha de login do backup foi atualizada recentemente através do painel da web, ou através do próprio agente em outra máquina usando a mesma conta de usuário.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: informe o usuário para efetuar login no agente de backup na máquina afetada para atualizar as configurações.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 7: A senha de login do Windows foi atualizada recentemente.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: O usuário precisa atualizar a senha desse conjunto de backup em “Autenticação do usuário para Windows” por meio do agente.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Razão # 8: O agente Skybackup foi acidentalmente desinstalado da máquina.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Resolução: Reinstale o agente cliente e, em seguida, efetue login no agente com a conta do usuário original.')
BackupPerdidoTutorialContent.create(tutorial_id: BackupPerdidoTutorial.last.id, content: 'Obs: Se nenhuma das opções acima resolver o seu problema de backup perdido, entre em contato com nosso Suporte para solução de problemas.')
