Category.create(title: 'Webmail', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/1/Webmail-2.png', category: 'E-mail')
Tutorial.create(category_id: Category.last.id, title: 'Compor e-mail – funcionalidades', href: '/ajuda/email-corporativo/email/tutorial/compor-e-mail-funcionalidades')
Tutorial.create(category_id: Category.last.id, title: 'Como Inserir um anexo', href: '/ajuda/email-corporativo/email/tutorial/inserir-um-anexo')
Tutorial.create(category_id: Category.last.id, title: 'Como criar pastas', href: '/ajuda/email-corporativo/email/tutorial/como-criar-pastas')
Tutorial.create(category_id: Category.last.id, title: 'Como esvaziar uma pasta', href: '/ajuda/email-corporativo/email/tutorial/como-esvaziar-uma-pasta')
Tutorial.create(category_id: Category.last.id, title: 'Como criar filtros', href: '/ajuda/email-corporativo/email/tutorial/como-criar-filtros')
Tutorial.create(category_id: Category.last.id, title: 'Mensagem de férias', href: '/ajuda/email-corporativo/email/tutorial/mensagem-de-ferias')
Tutorial.create(category_id: Category.last.id, title: 'Como trocar a senha', href: '/ajuda/email-corporativo/email/tutorial/como-trocar-a-senha')
Tutorial.create(category_id: Category.last.id, title: 'Como desabilitar a confirmação de entrega ', href: '/ajuda/email-corporativo/email/tutorial/como-desabilitar-a-confirmacao-de-entrega')
Tutorial.create(category_id: Category.last.id, title: 'Inserir ou trocar foto no Webmail', href: '/ajuda/email-corporativo/email/tutorial/inserir-ou-trocar-foto-no-webmail')
Tutorial.create(category_id: Category.last.id, title: 'Como pré-configurar e utilizar uma resposta', href: '/ajuda/email-corporativo/email/tutorial/como-pre-configurar-e-utilizar-uma-resposta')
Tutorial.create(category_id: Category.last.id, title: 'Como importar contatos', href: '/ajuda/email-corporativo/email/tutorial/como-importar-contatos')
Tutorial.create(category_id: Category.last.id, title: 'Regras de exclusão - Pasta Lixeira & Pasta Spam', href: '/ajuda/email-corporativo/email/tutorial/regras-de-exclusao')
Tutorial.create(category_id: Category.last.id, title: 'Calendário – funcionalidades', href: '/ajuda/email-corporativo/email/tutorial/calendario-funcionalidades')
Tutorial.create(category_id: Category.last.id, title: 'Como criar um novo calendário', href: '/ajuda/email-corporativo/email/tutorial/como-criar-um-novo-calendario')
Tutorial.create(category_id: Category.last.id, title: 'Como criar eventos no calendário', href: '/ajuda/email-corporativo/email/tutorial/como-criar-eventos-no-calendario')
Tutorial.create(category_id: Category.last.id, title: 'Contatos – funcionalidades', href: '/ajuda/email-corporativo/email/tutorial/contatos-funcionalidades')
Tutorial.create(category_id: Category.last.id, title: 'Como criar um contato', href: '/ajuda/email-corporativo/email/tutorial/como-criar-um-contato')
Tutorial.create(category_id: Category.last.id, title: 'Como exportar um contato', href: '/ajuda/email-corporativo/email/tutorial/como-exportar-um-contato')
Tutorial.create(category_id: Category.last.id, title: 'Como importar um contato', href: '/ajuda/email-corporativo/email/tutorial/como-importar-um-contato')
Tutorial.create(category_id: Category.last.id, title: 'Como criar um grupo de contatos', href: '/ajuda/email-corporativo/email/tutorial/como-criar-um-grupo-de-contatos')
Tutorial.create(category_id: Category.last.id, title: 'Como exportar um grupo de contatos', href: '/ajuda/email-corporativo/email/tutorial/como-exportar-um-grupo-de-contatos')
Tutorial.create(category_id: Category.last.id, title: 'Como criar e usar uma tarefa', href: '/ajuda/email-corporativo/email/tutorial/como-criar-e-usar-uma-tarefa')
Tutorial.create(category_id: Category.last.id, title: 'Informações do usuário', href: '/ajuda/email-corporativo/email/tutorial/informacoes-do-usuario')
Tutorial.create(category_id: Category.last.id, title: 'Preferências', href: '/ajuda/email-corporativo/email/tutorial/preferencias')
Tutorial.create(category_id: Category.last.id, title: 'Pastas', href: '/ajuda/email-corporativo/email/tutorial/pastas')
Tutorial.create(category_id: Category.last.id, title: 'Respostas', href: '/ajuda/email-corporativo/email/tutorial/respostas')
Tutorial.create(category_id: Category.last.id, title: 'Senha', href: '/ajuda/email-corporativo/email/tutorial/senha')
Tutorial.create(category_id: Category.last.id, title: 'Filtros', href: '/ajuda/email-corporativo/email/tutorial/filtros')
Tutorial.create(category_id: Category.last.id, title: 'Férias', href: '/ajuda/email-corporativo/email/tutorial/ferias')
Tutorial.create(category_id: Category.last.id, title: 'Identidade', href: '/ajuda/email-corporativo/email/tutorial/identidade')
Category.create(title: 'Clientes de email', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/2/Cliente-2-100x100.png', category: 'Configuração')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2016 IMAP Automática', href: '/ajuda/email-corporativo/email/tutorial/outlook-2016-imap-automatica')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2013 IMAP Automática', href: '/ajuda/email-corporativo/email/tutorial/outlook-2013-imap-automatica')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2016 IMAP Manual', href: '/ajuda/email-corporativo/email/tutorial/outlook-2016-imap-manual')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2013 IMAP Manual', href: '/ajuda/email-corporativo/email/tutorial/outlook-2013-imap-manual')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2016 POP3', href: '/ajuda/email-corporativo/email/tutorial/outlook-2016-pop3')
Tutorial.create(category_id: Category.last.id, title: 'Outlook 2013 POP3', href: '/ajuda/email-corporativo/email/tutorial/outlook-2013-pop3')
Tutorial.create(category_id: Category.last.id, title: 'POP3 em vários computadores', href: '/ajuda/email-corporativo/email/tutorial/pop3-em-varios-computadores')
Tutorial.create(category_id: Category.last.id, title: 'Mozilla Thunderbird LDAP', href: '/ajuda/email-corporativo/email/tutorial/mozilla-thunderbird-ldap')
Tutorial.create(category_id: Category.last.id, title: 'Configuração IMAP Automática – Aplicativo Nativo do Windows (Email)', href: '/ajuda/email-corporativo/email/tutorial/configuracao-imap-automatica')
Tutorial.create(category_id: Category.last.id, title: ' Importando e exportando PST no Outlook 2016/2013', href: '/ajuda/email-corporativo/email/tutorial/importando-e-exportando-pst-no-outlook')
Tutorial.create(category_id: Category.last.id, title: ' Eliminar itens excluídos no IMAP - Outlook 2007', href: '/ajuda/email-corporativo/email/tutorial/eliminar-itens-excluidos-no-imap')
Tutorial.create(category_id: Category.last.id, title: 'Confirmação de entrega – Outlook', href: '/ajuda/email-corporativo/email/tutorial/confirmacao-de-entrega')
Tutorial.create(category_id: Category.last.id, title: 'Anexos .Dat, assinatura como anexo.', href: '/ajuda/email-corporativo/email/tutorial/anexos')
Tutorial.create(category_id: Category.last.id, title: 'Mac Mail IMAP', href: '/ajuda/email-corporativo/email/tutorial/mac-mail-imap')
Tutorial.create(category_id: Category.last.id, title: 'MAC Outlook 2016 LDAP', href: '/ajuda/email-corporativo/email/tutorial/mac-outlook-2016-ldap')
Tutorial.create(category_id: Category.last.id, title: 'Como ver o cabeçalho original da mensagem no Outlook', href: '/ajuda/email-corporativo/email/tutorial/como-ver-o-cabecalho-original')
Tutorial.create(category_id: Category.last.id, title: 'Alterando os tamanhos padrão pst e ost', href: '/ajuda/email-corporativo/email/tutorial/alterando-os-tamanhos-padrao-pst-e-ost')
Tutorial.create(category_id: Category.last.id, title: 'Corrigindo erro de certificado no Iphone - A identidade não pode ser verificada', href: '/ajuda/email-corporativo/email/tutorial/corrigindo-erro-de-certificado-no-iphone')
Tutorial.create(category_id: Category.last.id, title: 'Corrigindo erro de certificado no Aplicativo GMAIL', href: '/ajuda/email-corporativo/email/tutorial/corrigindo-erro-de-certificado-no-aplicativo-gmail')
Tutorial.create(category_id: Category.last.id, title: 'Configurar Thunderbird de forma automática', href: '/ajuda/email-corporativo/email/tutorial/configurar-thunderbird-de-forma-automatica')
Category.create(title: 'Smartphone', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/3/Smatphone-4-100x100.png', category: 'IPhone')
Tutorial.create(category_id: Category.last.id, title: 'IPhone IMAP', href: '/ajuda/email-corporativo/email/tutorial/iphone-imap')
Tutorial.create(category_id: Category.last.id, title: 'Configurar Outlook App no IPhone via Protocolo IMAP', href: '/ajuda/email-corporativo/email/tutorial/configurar-outlook-app-no-iphone-via-protocolo-imap')
Tutorial.create(category_id: Category.last.id, title: 'Configurar calDAV - Iphone', href: '/ajuda/email-corporativo/email/tutorial/configurar-caldav')
Tutorial.create(category_id: Category.last.id, title: 'Android skymail IMAP', href: '/ajuda/email-corporativo/email/tutorial/android-skymail-imap')
Tutorial.create(category_id: Category.last.id, title: 'Sincronizando Calendário no Android 7.0', href: '/ajuda/email-corporativo/email/tutorial/sincronizando-calendario-no-android')
Tutorial.create(category_id: Category.last.id, title: 'Windows Phone IMAP', href: '/ajuda/email-corporativo/email/tutorial/windows-phone-imap')
