Category.create(name: 'Configurações', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/21/Configura__es-100x100.png')
Tutorial.create(category_id: Category.last.id, title: 'Relatório', href: '/ajuda/backup/tutoriais-para-backup/tutorial/relatorio')
Tutorial.create(category_id: Category.last.id, title: 'Instalação do client SkyBackup', href: '/ajuda/backup/tutoriais-para-backup/tutorial/instalacao-do-client-skybackup')
Tutorial.create(category_id: Category.last.id, title: 'Criando conjunto de backup', href: '/ajuda/backup/tutoriais-para-backup/tutorial/criando-conjunto-de-backup')
Tutorial.create(category_id: Category.last.id, title: 'Configurações do Conjunto de Backup', href: '/ajuda/backup/tutoriais-para-backup/tutorial/configuracoes-do-conjunto-de-backup')
Tutorial.create(category_id: Category.last.id, title: 'Como executar um conjunto de backup', href: '/ajuda/backup/tutoriais-para-backup/tutorial/como-executar-um-conjunto-de-backup')
Tutorial.create(category_id: Category.last.id, title: 'Restauração de Arquivos', href: '/ajuda/backup/tutoriais-para-backup/tutorial/restauracao-de-arquivos')
Tutorial.create(category_id: Category.last.id, title: 'Criando Conjunto de Backup Sql Server', href: '/ajuda/backup/tutoriais-para-backup/tutorial/criando-conjunto-de-backup-sql-server')
Tutorial.create(category_id: Category.last.id, title: 'Restauração Sql Server', href: '/ajuda/backup/tutoriais-para-backup/tutorial/restauracao-sql-server')
Tutorial.create(category_id: Category.last.id, title: 'Criar novo usuário do Backup Revenda', href: '/ajuda/backup/tutoriais-para-backup/tutorial/criar-novo-usuario-do-backup-revenda')
Tutorial.create(category_id: Category.last.id, title: 'Criar novo usuário do Backup Cliente', href: '/ajuda/backup/tutoriais-para-backup/tutorial/criar-novo-usuario-do-backup-cliente')
Category.create(name: 'Instalações', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/22/Instala__es-2-100x100.png')
Tutorial.create(category_id: Category.last.id, title: 'Customização do Backup', href: '/ajuda/backup/tutoriais-para-backup/tutorial/customizacao-do-backup')
Category.create(name: 'Soluções de erros', img_src: 'https://cdn1.agenciaw3.digital//uploads/type_help/icon/23/Solu__es-de-erro-100x100.png')
Tutorial.create(category_id: Category.last.id, title: 'Backup Perdido', href: '/ajuda/backup/tutoriais-para-backup/tutorial/backup-perdido')
Tutorial.create(category_id: Category.last.id, title: 'Backup interrompido', href: '/ajuda/backup/tutoriais-para-backup/tutorial/backup-interrompido')
