CustomizationBackupTutorial.create(title: 'Customização do Backup', date: '17 / 02 / 2020')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Customização SkyBackup')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Configurações necessárias para Customização SkyBackup')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Segue abaixo alguns exemplos de como é o layout do nosso backup atual, vamos deixar também um exemplo de um cliente que utiliza a solução personalizada, todas essas cores podem ser alteradas.')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Tela de login original – Skymail')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Área principal original – Skymail')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Tela de login – Um dos nossos clientes')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Área principal – um dos nossos clientes')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Abaixo as imagens necessárias para adicionar ao painel web, cliente de backup servidor e desktop, mantendo assim as configurações de layout desejadas.')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipos de interface Web (Descrição, formato, tamanho);')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipo de interface de usuário (png 200 x 72 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipo do relatório enviado por email (gif – 129 x 40 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipo painel (png – 24 x 24 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipo cliente para servidor (png – 18 x 18 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipo cliente para computador (png – 18 x 18 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipos de Interface – Cliente Servidor (Descrição, formato, tamanho);')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logo tela “sobre” (png 144 x 33 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Background tela login (png 1016 x 734 px) – Opcional utilizar o nosso, alterando apenas a cor')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logo tela login (png 200 x 60 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logo principal (png 32 x 32 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logo principal horizontal (png 148 x 33 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Carregamento de abertura (png 420 x 240 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Pequenos logos do sistema do cliente em 4 tamanhos, visualmente iguais -(png24 x 24 px) (32 x 32 px) (48 x 48 px) (16 x 16 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipos de sistema operacional Windows – Cliente Servidor (Descrição, formato, tamanho, detalhe):')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone System Tray “Bandeja do Sistema” 1 (ico 16 x 16 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone System Tray “Bandeja do Sistema” 2 (ico 16 x 16 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone System Tray “Bandeja do Sistema” 3 (ico 16 x 16 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone System Tray “Bandeja do Sistema” 4 (ico 16 x 16 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Os 4 ícones do System Tray precisam ser iguais, porém com intensidade de luz da mais baixa para a mais alta, formando uma animação.')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone que fica na barra dos programas abertos (ico 64 x 64 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Logotipos de instalação Windows – Client Servidor (Descrição, formato, tamanho):')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Backgroud Instalação (bmp 164 x 337 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Icone de Desktop (ico 256 x 256 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Icone de Instalação (ico 256 x 256 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Icone Tela de Instalação (bmp 55 x 58 px)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Ícone de Desinstalação (bmp 256 x 256 px – Truecolor mais transparência de canal alfa)')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Caso seja necessário a parte de Linux, Synology e Mac podemos orientar como fazer a alteração dos ícones padrões de sistema após o trial')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'Vou deixar abaixo o nosso link de download do cliente de servidor e desktop.')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'https://backup-ha.skymail.net.br/cbs/download/obm-win.zip – Cliente Servidor')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'https://backup-ha.skymail.net.br/cbs/download/acb-win.zip – Cliente desktop')
CustomizationBackupTutorialContent.create(tutorial_id: CustomizationBackupTutorial.last.id, content: 'https://backup-ha.skymail.net.br/ – acesso ao Painel')
